<div class="container mx-auto my-10">

<?php if ($this->tarea): ?>
    <h1 class="text-center text-3xl font-semibold mb-4">Detalles de la Tarea</h1>
    <div class="bg-white rounded-lg shadow divide-y divide-gray-200 max-w-sm mx-auto">
        <div class="px-6 py-4">
            <div class="flex justify-between">
                <span class="font-semibold text-lg"><?php echo ($this->tarea['Titulo']); ?></span>
                <span class="text-gray-500 text-xs">Fecha: <?php echo ($this->tarea['Fecha']); ?></span><br>
            </div>
            
            <div class="flex justify-between">
            <span class="text-gray-500 text-xs">De: <?php echo ($this->tarea['Hora_inicio']); ?> hasta: <?php echo ($this->tarea['Hora_final']); ?></span>
            </div>
            <p class="text-gray-700"><?php echo ($this->tarea['Descripcion']); ?></p>
            <div class="mt-4 flex items-center justify-between">
                <p class="text-sm font-medium text-gray-500">Status: <span class="text-green-600"><?php echo ($this->tarea['Status']); ?></span></p>
                <a href="<?php echo $this->baseUrl(); ?>/tarea/edita?id=<?php echo $this->tarea['Id'];?>" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Editar</a>
            </div>
        </div>
    </div>
    <div class="max-w-sm mx-auto mt-3">
        <a href="<?php echo $this->baseUrl(); ?>/tarea" class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">Volver a la lista</a>
    </div>
<?php else: ?>
    <p><?php echo ($this->mensaje); ?></p>
    <div class="max-w-sm mx-auto mt-3">
        <a href="<?php echo $this->baseUrl(); ?>/tarea" class="focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">Volver a la lista</a>
    </div>
    <?php endif; ?>
</div>