-- MySQL Script generated by MySQL Workbench
-- Thu May 30 12:37:33 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` ;
USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Proveidor` (
  `idProveidor` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProveidor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Clients` (
  `idClients` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `data` DATE NULL,
  `recomanat` INT NULL,
  PRIMARY KEY (`idClients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Ulleres` (
  `idUlleres` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(45) NOT NULL,
  `marca` VARCHAR(45) NULL,
  `graduacio_dreta` DECIMAL(4,2) NOT NULL,
  `graduacio_esquerra` DECIMAL(4,2) NOT NULL,
  `montura` ENUM('flotant', 'pasta', 'metal') NULL,
  `color_montura` VARCHAR(45) NULL,
  `color_vidre_dreta` VARCHAR(45) NULL,
  `color_vidre_esquerra` VARCHAR(45) NULL,
  `preu` DECIMAL(5,2) NULL,
  `proveidor_id` INT NULL,
  `Proveidor_idProveidor` INT NOT NULL,
  PRIMARY KEY (`idUlleres`),
  INDEX `fk_Ulleres_Proveidor1_idx` (`Proveidor_idProveidor` ASC) VISIBLE,
  CONSTRAINT `fk_Ulleres_Proveidor1`
    FOREIGN KEY (`Proveidor_idProveidor`)
    REFERENCES `optica`.`Proveidor` (`idProveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Empleat` (
  `idEmpleat` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `cognoms` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpleat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Contacte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Contacte` (
  `idContacte` INT NOT NULL AUTO_INCREMENT,
  `tipus` ENUM('proveidor', 'client', 'empleat') NULL,
  `carrer` VARCHAR(45) NULL,
  `numero` INT NULL,
  `pis` VARCHAR(45) NULL,
  `porta` VARCHAR(45) NULL,
  `ciutat` VARCHAR(45) NULL,
  `codi_postal` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NULL,
  `fax` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Empleat_idEmpleat` INT NOT NULL,
  `Clients_idClients` INT NOT NULL,
  `Proveidor_idProveidor` INT NOT NULL,
  PRIMARY KEY (`idContacte`),
  INDEX `fk_Contacte_Empleat1_idx` (`Empleat_idEmpleat` ASC) VISIBLE,
  INDEX `fk_Contacte_Clients1_idx` (`Clients_idClients` ASC) VISIBLE,
  INDEX `fk_Contacte_Proveidor1_idx` (`Proveidor_idProveidor` ASC) VISIBLE,
  CONSTRAINT `fk_Contacte_Empleat1`
    FOREIGN KEY (`Empleat_idEmpleat`)
    REFERENCES `optica`.`Empleat` (`idEmpleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contacte_Clients1`
    FOREIGN KEY (`Clients_idClients`)
    REFERENCES `optica`.`Clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contacte_Proveidor1`
    FOREIGN KEY (`Proveidor_idProveidor`)
    REFERENCES `optica`.`Proveidor` (`idProveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `optica`.`Vendes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`Vendes` (
  `idVendes` INT NOT NULL AUTO_INCREMENT,
  `Empleat_idEmpleat` INT NOT NULL,
  `Clients_idClients` INT NOT NULL,
  `Ulleres_idUlleres` INT NOT NULL,
  PRIMARY KEY (`idVendes`, `Ulleres_idUlleres`),
  INDEX `fk_Vendes_Empleat1_idx` (`Empleat_idEmpleat` ASC) VISIBLE,
  INDEX `fk_Vendes_Clients1_idx` (`Clients_idClients` ASC) VISIBLE,
  INDEX `fk_Vendes_Ulleres1_idx` (`Ulleres_idUlleres` ASC) VISIBLE,
  CONSTRAINT `fk_Vendes_Empleat1`
    FOREIGN KEY (`Empleat_idEmpleat`)
    REFERENCES `optica`.`Empleat` (`idEmpleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendes_Clients1`
    FOREIGN KEY (`Clients_idClients`)
    REFERENCES `optica`.`Clients` (`idClients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendes_Ulleres1`
    FOREIGN KEY (`Ulleres_idUlleres`)
    REFERENCES `optica`.`Ulleres` (`idUlleres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
